######################################################################
# Automatically generated by qmake (1.07a) Fri Mar 15 09:59:38 2013
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += editpreference.ui.h gpu.h
INTERFACES += editpreference.ui
SOURCES += main.cpp
